site_name: 'HBS Grid User Guide'
site_url: 'https://hbs-rcs.github.io/hbsgrid-docs/'
copyright: Copyright &copy; President & Fellows of Harvard College.
repo_url: 'https://github.com/hbs-rcs/hbsgrid-docs'
edit_uri: '/hbs-rcs/hbsgrid-docs/edit/v2.5/docs/'
docs_dir: 'docs'
remote_branch: gh-pages

nav:
  - Compute Cluster and Data Storage: 'index.md'
  - Compute Cluster:
    - compute-cluster/overview.md
    - compute-cluster/copying-and-extracting-files.md
    - compute-cluster/logging-in.md
    - compute-cluster/quick-start.md
    - compute-cluster/request-an-account.md
    - compute-cluster/techbenefits.md
    - Running Jobs:
      - compute-cluster/running-jobs/overview.md
      - compute-cluster/running-jobs/guidelines-for-choosing-resources.md
      - compute-cluster/running-jobs/monitoring.md
      - compute-cluster/running-jobs/running-a-program-submitting-a-job.md
      - compute-cluster/running-jobs/scaling-work.md
    - Selecting Software:
      - compute-cluster/selectingsoftware/overview.md
      - compute-cluster/selectingsoftware/conda.md
      - Machine Learning: compute-cluster/selectingsoftware/ML.md
      - compute-cluster/selectingsoftware/git.md
      - compute-cluster/selectingsoftware/julia.md
      - compute-cluster/selectingsoftware/jupyter.md
      - compute-cluster/selectingsoftware/r-and-python-hbsgrid.md
      - compute-cluster/selectingsoftware/rclone.md
      - compute-cluster/selectingsoftware/sasconnect.md
      - compute-cluster/selectingsoftware/stata.md
    - other-research-computing-environments.md
  - Database Server:
    - database-server/overview.md
    - database-server/configuration-files-recommended-for-connecting.md
    - database-server/mysql-client.md
    - database-server/navicat.md
    - database-server/nomachine.md
    - database-server/odbc.md
    - database-server/python.md
    - database-server/r.md
    - database-server/sas.md
    - database-server/stata.md
    - database-server/terminal.md
  - Research Storage:
    - research-storage/overview.md
    - research-storage/accessing-spaces-and-storage.md
    - research-storage/transferring-data.md
    - research-storage/working-with-spaces-files-and-folders.md

theme:
  name: material
  features:
    - toc.integrate
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
  palette:
    scheme: hbs

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - meta
  - tables
  - toc:
      toc_depth: 2
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - mdx_gh_links:
      user: mkdocs
      repo: mkdocs
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.details

extra:
  analytics:
    provider: google
    property: G-3P5QKSCGVL
  version:
    provider: mike
          
plugins:
  - search
  - mike:
      version_selector: true
